apiVersion: v1
kind: Service
metadata:
  name: external-app
spec:
  externalName: app-service.myapp-application
  type: ExternalName

---
apiVersion: v1
kind: Service
metadata:
  name: external-jwt
spec:
  externalName: jwt-auth-service.myapp-application
  type: ExternalName

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # "Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    - match: PathPrefix(`/jwt/login`)
      kind: Rule
      services:
        - name: external-jwt
          port: 3003
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: external-app
          port: 3000
      middlewares:
        - name: forward-auth