apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    purpose: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      purpose: {{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        purpose: {{ .Chart.Name }}-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Chart.Name }}-pdport
              containerPort: 8000
              protocol: TCP
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-cm
                  key: secret
            - name: JWT_FORWARD_HEADER_NAME
              value: {{ .Values.jwt.reponseHeader | default "X-JWT-UserID" | quote }}
            - name: JWT_KEY_IN_PAYLOAD
              value: {{ .Values.jwt.body.desirableKey.name | default "uid" | quote }}
            - name: JWT_FORWARD_DEFAULT_VALUE
              value: {{ .Values.jwt.body.desirableKey.defaultValue | default "0" | quote }}
            - name: JWT_TTL
              value: {{ .Values.jwt.ttl | default "60000" | quote }}
            - name: JWT_LOGIN_SERVICE
              value: {{ .Values.jwt.login.service | default "localhost" | quote }}
            - name: JWT_LOGIN_PORT
              value: {{ .Values.jwt.login.port | default "8080" | quote }}