apiVersion: v1
kind: ConfigMap
# see details https://stackoverflow.com/questions/58449442/create-or-update-existing-postgres-db-container-through-kubernetes-job
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:homework_db.sql: {}
      manager: kubectl
      operation: Update
  name: postgresql-migration
  labels:
    {{- include "hw02chart.labels" . | nindent 4 }}
data:
  homework_db.sql: |-
    -- create user homeuser with password 'password';
    drop database if exists homeworkdb;
    create database homeworkdb with owner=homeuser CONNECTION LIMIT = 3;
    \connect homeworkdb;
    alter default privileges grant all on tables to homeuser;
    alter default privileges grant all on sequences to homeuser;

    create table my_users(
        user_id integer primary key not null,
        first_name varchar(256) not null,
        last_name varchar(256) not null,
        email varchar(200) not null,
        phone varchar(14) not null
    );
    create sequence my_users_seq increment 1 start 1;
