kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.psql.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    # we talk here about path inside minikube (minikube ssh)
    path: {{ .Values.psql.hostDir }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.psql.capacity.storage }}