repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
#  - name: stable
#    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - # prometheus
    name: prometheus-init
    chart: prometheus-community/kube-prometheus-stack
    namespace: metrics
    createNamespace: true
    values:
      - ./values/prometheus-init.yaml

  - # expose prometheus
    name: prometheus-ingress-expose
    namespace: metrics
    createNamespace: true
    chart: ./charts/prometheus-ingress-expose
    values:
      - ./values/prometheus-ingress-expose.yaml

  - # database migration
    name: postgresql-init
    namespace: myapp-database
    createNamespace: true
    chart: ./charts/postgresql-init
    values:
      - ./values/postgresql-init.yaml

  - # app
    name: app
    namespace: myapp-application
    createNamespace: true
    chart: ./charts/app
    values:
      - ./values/app.yaml