repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
#  - name: prometheus-community
#    url: https://prometheus-community.github.io/helm-charts
#  - name: stable
#    url: https://kubernetes-charts.storage.googleapis.com

releases:
#  - name: myzookeeper
#    chart: bitnami/zookeeper
#    namespace: zookaf
#    createNamespace: true

  - name: mykafka
    chart: bitnami/kafka
    namespace: zookaf
    createNamespace: true

  - name: capp
    namespace: zookaf
    createNamespace: true
    chart: ./charts/command-app

#  - name: mytraefik
#    chart: ./charts/mytraefik
#    namespace: traefikns
#    createNamespace: true
#    values:
#      - ./values/mytraefik.yaml
#
#  - name: jwt-auth
#    namespace: myapp-application
#    createNamespace: true
#    chart: ./charts/jwt-auth
#    values:
#      - ./values/jwt-auth.yaml

#  - # prometheus
#    name: prometheus-init
#    chart: prometheus-community/kube-prometheus-stack
#    namespace: metrics
#    createNamespace: true
#    values:
#      - ./values/prometheus-init.yaml
#
#  - # expose prometheus
#    name: prometheus-ingress-expose
#    namespace: metrics
#    createNamespace: true
#    chart: ./charts/prometheus-ingress-expose
#    values:
#      - ./values/prometheus-ingress-expose.yaml
#
#  - # database migration
#    name: postgresql-init
#    namespace: myapp-database
#    createNamespace: true
#    chart: ./charts/postgresql-init
#    values:
#      - ./values/postgresql-init.yaml
#
#  - # app
#    name: app
#    namespace: myapp-application
#    createNamespace: true
#    chart: ./charts/app
#    values:
#      - ./values/app.yaml