repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mykafka
    chart: bitnami/kafka
    namespace: zookaf
    createNamespace: true

  - name: capp
    namespace: zookaf
    createNamespace: true
    chart: ./charts/command-app