{{- if .Values.postgresql.initdbScriptsConfigMap }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    {{- include "postgresql-init.labels" . | nindent 4 }}
type: Opaque
data:
  dbi-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  dbi-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}