apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-pod-web-server
  template:
    metadata:
      labels:
        app: label-pod-web-server
    spec:
      containers:
        - name: container-web-server
          image: turneps403/otus-spring-demo:v4
          ports:
            - name: port-web-server
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: port-web-server
              path: /ping
            initialDelaySeconds: 14
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: port-web-server
              path: /isready
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2