apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: turneps403/homework02:1.0.0
        name: myapp
        ports:
            - name: port-web-server
              containerPort: 8000
              protocol: TCP
        livenessProbe:
          httpGet:
            port: port-web-server
            path: /myactuator/health
          initialDelaySeconds: 14
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: port-web-server
            path: /myactuator/isready
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 2
        env:
          - name: APP_POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: dbi-user
          - name: APP_POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: dbi-password
          - name: APP_POSTGRESQL_HOST
            valueFrom:
              configMapKeyRef:
                name: myapp-configmap
                key: postgresql_host
          - name: APP_POSTGRESQL_PORT
            value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: service-web-server
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: port-web-server
  type: NodePort