apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-demo
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
        - name: hello-demo
          image: turneps403/otus-spring-demo:v2
          ports:
            - containerPort: 8080