replicaCount: 1
image:
  repository: turneps403/homework07
  tag: "1.0.0"
service:
  type: NodePort
  port: 3000
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: arch.homework
      paths:
        - /(.*)