{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prometheus-ingress-expose.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prometheus-ingress-expose.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ .service }}
              servicePort: {{ .port }}
    {{- end }}
{{- end }}