apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  dbi-user: {{ .Values.psql.user | b64enc | quote }}
  dbi-password: {{ .Values.psql.password | b64enc | quote }}
  dbi-database: {{ .Values.psql.database | b64enc | quote }}