postgresql:
  postgresqlUsername: homeuser
  postgresqlPassword: password
  fullnameOverride: mypostgresql
  persistence:
    enabled: true
    existingClaim: postgres-pv-claim
  volumePermissions:
    enabled: true
  replication:
    enabled: false
  initdbScriptsConfigMap: postgresql-migration



serviceAccount:
  create: false
replicaCount: 1
image:
  repository: turneps403/homework02
  tag: "1.0.0"
service:
  type: NodePort
  port: 80
autoscaling:
  enabled: false
psql:
  password: password
  user: homeuser
  database: homeworkdb
  hostDir: "/tmp/export"
  capacity:
    storage: 100M



ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - /otusapp/sivirinov(/|$)(.*)
